"""
Shared Utility Helpers for isolated stages
"""
import os
import shlex
from typing import Any, List
from nexus.core.task import Task
from nexus.utils.logger import get_logger

logger = get_logger(__name__)

_BARE_INTERPRETERS = {
    "python3", "python", "python2",
    "node", "ruby", "perl", "bash", "sh",
}

_CONFTEST_CONTENT = (
    "# Auto-generated by NEXUS\n"
    "# Empty conftest.py — tells pytest to add project root to sys.path\n"
)

def inject_conftest_if_needed(workspace: Any, task: Task) -> None:
    wdir = workspace.get_path()
    conftest_path = os.path.join(wdir, "conftest.py")
    if os.path.exists(conftest_path):
        return

    has_subdir_tests = any(
        fname.endswith(".py")
        and ("/" in fname or os.sep in fname)
        and os.path.basename(fname).startswith("test_")
        for fname in task.generated_files
    )
    if not has_subdir_tests:
        return

    try:
        with open(conftest_path, "w") as f:
            f.write(_CONFTEST_CONTENT)
        task.generated_files["conftest.py"] = _CONFTEST_CONTENT
        logger.info("Injected conftest.py")
    except OSError as e:
        logger.warning("Failed to inject conftest.py: %s", e)

def normalize_test_command(task: Task, workspace: Any) -> None:
    wdir = workspace.get_path()
    planned_cmd = task.plan.get("test_command", "").strip()
    resolved_cmd = resolve_test_command(planned_cmd, wdir)
    if resolved_cmd != planned_cmd:
        logger.info(
            "Normalized test_command: '%s' → '%s'", planned_cmd, resolved_cmd
        )
        task.plan["test_command"] = resolved_cmd

def resolve_test_command(planned_cmd: str, wdir: str) -> str:
    if planned_cmd:
        args = shlex.split(planned_cmd)
        if is_valid_command(args, wdir) and command_target_exists(args, wdir):
            return planned_cmd

    test_files = find_test_files(wdir)
    if test_files:
        return "pytest -v --tb=short"

    for name in ["main.py", "app.py", "run.py"]:
        if os.path.exists(os.path.join(wdir, name)):
            return f"python3 {name}"

    return ""

def command_target_exists(args: list, wdir: str) -> bool:
    if not args:
        return False
    executable = os.path.basename(args[0]).lower()
    if executable == "pytest":
        for arg in args[1:]:
            if not arg.startswith("-"):
                target = os.path.join(wdir, arg)
                if not os.path.exists(target):
                    return False
        return True
    if executable in _BARE_INTERPRETERS and len(args) >= 2:
        script = args[1]
        if not script.startswith("-"):
            return os.path.exists(os.path.join(wdir, script))
    return True

def is_valid_command(args: list, cwd: str) -> bool:
    if not args:
        return False
    executable = os.path.basename(args[0]).lower()
    if executable in _BARE_INTERPRETERS and len(args) == 1:
        return False
    return True

def find_test_files(wdir: str) -> List[str]:
    found = []
    try:
        for entry in os.scandir(wdir):
            if (
                entry.is_file()
                and entry.name.startswith("test_")
                and entry.name.endswith(".py")
            ):
                found.append(entry.name)
            elif entry.is_dir() and not entry.name.startswith("."):
                try:
                    for sub in os.scandir(entry.path):
                        if (
                            sub.is_file()
                            and sub.name.startswith("test_")
                            and sub.name.endswith(".py")
                        ):
                            found.append(os.path.join(entry.name, sub.name))
                except OSError:
                    pass
    except OSError:
        pass
    return found
