"""
nexus/core/engine.py
────────────────────
Task execution engine. Coordinates the full pipeline:
  route → plan → generate → install → test → fix_loop → complete

run() is a clean coordinator. Each pipeline stage is a private method.
"""
import os
import shlex
import json
from typing import List, Optional, Any

from nexus.ai.code_intel import CodeIntelligence
from nexus.ai.orchestrator import AIOrchestrator
from nexus.ai.router import IntentRouter, IntentType, IntentResult
from nexus.repair.classifier import classify_error
from nexus.core.exceptions import (
    MaxRetriesExceeded,
    NexusBaseException,
    OllamaConnectionError,
    SafetyViolation,
    TaskGenerationError,
    TaskPlanningError,
)
from nexus.core.task import Task, TaskResult, TaskStatus
from nexus.executor.safe_exec import ExecResult, create_task_venv, get_venv_executables, run_command
from nexus.executor.executor_factory import get_executor
from nexus.executor.validator import build_error_context, validate_result, ValidationResult
from nexus.executor.workspace import Workspace
from nexus.utils.config import config
from nexus.utils.history import TaskHistory
from nexus.memory.manager import get_memory
from nexus.utils.logger import get_logger

logger = get_logger(__name__)

_BARE_INTERPRETERS = {
    "python3", "python", "python2",
    "node", "ruby", "perl", "bash", "sh",
}

_CONFTEST_CONTENT = (
    "# Auto-generated by NEXUS\n"
    "# Empty conftest.py — tells pytest to add project root to sys.path\n"
)


class TaskEngine:
    def __init__(self, context: Optional[Any] = None) -> None:
        import atexit

        self.ai = AIOrchestrator()
        self.context = context
        self.history = TaskHistory()
        self.memory  = get_memory()
        self.code_intel = CodeIntelligence(self.ai)
        self._executor = get_executor()
        logger.info("TaskEngine initialized with %s", self._executor.__class__.__name__)

        try:
            from nexus.executor.docker_exec import cleanup_orphaned_containers, is_docker_available
            if is_docker_available():
                cleaned = cleanup_orphaned_containers()
                if cleaned > 0:
                    logger.warning(
                        "Cleaned up %d orphaned containers from previous session", cleaned
                    )
            atexit.register(self._shutdown_cleanup)
        except ImportError:
            logger.debug("Docker SDK not found — skipping container cleanup")

    # ══════════════════════════════════════════════════════════════════════════
    # Public entry point
    # ══════════════════════════════════════════════════════════════════════════

    def run(self, user_input: str, intent_result: Any = None) -> Any:
        # ── Input guard: oversized input defaults to CHAT, no LLM call ────────
        MAX_INPUT_CHARS = 8000
        if len(user_input) > MAX_INPUT_CHARS:
            logger.warning(
                "Input too long (%d chars) — truncating to %d and defaulting to CHAT",
                len(user_input), MAX_INPUT_CHARS,
            )
            user_input = user_input[:MAX_INPUT_CHARS]
            # Skip routing — oversized inputs are never task requests
            if intent_result is None:
                from nexus.ai.router import IntentResult, IntentType
                intent_result = IntentResult(
                    intent=IntentType.CHAT,
                    confidence=1.0,
                    reasoning="Input exceeded maximum length — defaulted to CHAT",
                    raw_input=user_input,
                )

        task = Task(raw_input=user_input)

        logger.info("=" * 60)
        logger.info("Starting task [%s]: %s", task.id, task.raw_input[:60])
        logger.info("=" * 60)

        workspace = None

        try:
            # ── Intent routing ──────────────────────────────────────────────
            if intent_result is None:
                router = IntentRouter(self.ai)
                intent_result = router.route(task.raw_input)

            _intent = intent_result.intent
            # Normalize intent to string safely — handles IntentType enum,
            # plain string (from mocks), and any duck-typed object
            if isinstance(_intent, IntentType):
                intent_val = _intent.value
            elif isinstance(_intent, str):
                intent_val = _intent.upper()
            elif hasattr(_intent, "value"):
                intent_val = str(_intent.value).upper()
            else:
                intent_val = str(_intent).upper()
            task.intent = intent_result

            if self.context:
                self.context.add_message("user", task.raw_input)

            # ── Non-task intents ────────────────────────────────────────────
            if intent_val != IntentType.TASK.value:
                logger.info("Non-task intent detected: %s", intent_val)
                # Normalize intent_result so _handle_non_task always gets
                # a real IntentResult regardless of what the caller passed
                from nexus.ai.router import IntentResult
                if not isinstance(intent_result, IntentResult):
                    try:
                        _norm_intent = IntentType(intent_val)
                    except ValueError:
                        _norm_intent = IntentType.CHAT
                    intent_result = IntentResult(
                        intent=_norm_intent,
                        confidence=1.0,
                        reasoning="Normalized from mock/string",
                        raw_input=task.raw_input,
                    )
                    task.intent = intent_result
                res = self._handle_non_task(task, intent_result)
                if self.context:
                    self.context.add_message("assistant", res.result.summary)
                    self.context.add_task_result(
                        task.id, res.result.summary, intent_val, res.status.name
                    )
                return res

            # ── Workspace setup ─────────────────────────────────────────────
            workspace = Workspace(task.id)
            workspace.create()
            task.workspace_path = workspace.get_path()
            venv_path = create_task_venv(workspace.get_path())
            task.venv_executables = get_venv_executables(venv_path)

            # ── Pipeline stages ─────────────────────────────────────────────
            self._stage_plan(task)
            self._stage_generate(task, workspace)

            install_result = self._stage_install(task, workspace)
            if not validate_result(install_result, "install"):
                install_vr = validate_result(install_result, "install")
                error_ctx = build_error_context(install_vr, "install")
                from nexus.core.contracts import ExecutionOutput
                task.record_execution(ExecutionOutput(
                    returncode=install_result.returncode,
                    stdout=install_result.stdout,
                    stderr=install_result.stderr,
                    timed_out=install_result.timed_out,
                ))
                self._fix_loop(task, workspace, error_ctx)
                return task

            task.transition(TaskStatus.VALIDATING)
            vr = self._stage_test(task, workspace)

            if vr.is_success:
                self._stage_complete(task, workspace, iterations=task.fix_iteration)
            else:
                error_ctx = build_error_context(vr, "test")
                from nexus.core.contracts import ExecutionOutput
                task.record_execution(ExecutionOutput(
                    returncode=vr.stage1_result.returncode,
                    stdout=vr.stage1_result.stdout,
                    stderr=vr.stage1_result.stderr,
                    timed_out=getattr(vr.stage1_result, "timed_out", False),
                ))
                if getattr(vr.stage1_result, "timed_out", False) or vr.stage1_result.returncode == -1:
                    self._fail_task(task, "Execution timed out — task killed (non-fixable)")
                    return task
                if getattr(vr.stage1_result, "security_blocked", False):
                    self._fail_task(
                        task,
                        f"Security violation blocked execution (non-fixable): "
                        f"{vr.stage1_result.stderr[:200]}",
                    )
                    return task
                self._fix_loop(task, workspace, error_ctx, vr)

        except OllamaConnectionError as e:
            self._fail_task(task, f"Ollama unreachable: {e}")
        except (TaskPlanningError, TaskGenerationError) as e:
            self._fail_task(task, f"AI error: {e}")
        except SafetyViolation as e:
            self._fail_task(task, f"Security blocked: {e}")
        except MaxRetriesExceeded as e:
            self._fail_task(task, str(e))
        except NexusBaseException as e:
            self._fail_task(task, f"NEXUS error: {e}")
        except Exception as e:
            logger.exception("Unexpected error in engine")
            self._fail_task(task, f"Unexpected: {e}")

        finally:
            if self.context and task.result:
                intent_obj = getattr(task, "intent", None)
                intent_type = getattr(intent_obj, "intent", "UNKNOWN")
                intent_str = (
                    intent_type.value
                    if hasattr(intent_type, "value")
                    else str(intent_type)
                )
                self.context.add_task_result(
                    task.id, task.result.summary, intent_str, task.status.name
                )

            self.history.record(
                task,
                self.context.session_id if self.context else "NO_SESSION",
            )
            # Persist to queryable memory store
            _intent_str = (
                task.intent.intent.value
                if task.intent and hasattr(task.intent, 'intent')
                else str(task.intent) if task.intent else 'UNKNOWN'
            )
            self.memory.record_execution(
                session_id=self.context.session_id if self.context else 'NO_SESSION',
                intent=_intent_str,
                raw_input=task.raw_input,
                status=task.status.name,
                summary=task.result.summary if task.result else '',
                fix_attempts=task.fix_iteration,
            )

            if task.status == TaskStatus.FAILED and workspace is not None:
                try:
                    workspace.cleanup()
                except Exception:
                    logger.warning(
                        "Workspace cleanup failed for task %s", task.id
                    )

        return task

    # ══════════════════════════════════════════════════════════════════════════
    # Pipeline stage methods
    # ══════════════════════════════════════════════════════════════════════════

    def _stage_plan(self, task: Task) -> None:
        """
        Stage: PLANNING
        Call the AI planner and store the plan on the task.
        Raises TaskPlanningError on failure.
        """
        task.transition(TaskStatus.PLANNING)
        plan = self.ai.generate_plan(task.raw_input, context=self.context)
        task.plan = plan
        logger.info("Plan stage complete: %s", plan.get("description", ""))

    def _stage_generate(self, task: Task, workspace: Workspace) -> None:
        """
        Stage: GENERATING
        Generate code files, write them to workspace, normalize test command.
        Raises TaskGenerationError on failure.
        """
        task.transition(TaskStatus.GENERATING)
        files = self.ai.generate_code(task.plan, context=self.context)
        task.generated_files = files
        workspace.write_files(files)
        self._inject_conftest_if_needed(workspace, task)
        self._normalize_test_command(task, workspace)
        logger.info(
            "Generate stage complete: %d files written", len(files)
        )

    def _stage_install(self, task: Task, workspace: Workspace) -> ExecResult:
        """
        Stage: EXECUTING (install step)
        Run pip install if requirements.txt exists.
        Returns ExecResult — caller decides whether to enter fix loop.
        """
        task.transition(TaskStatus.EXECUTING)
        result = self._run_install(task.plan, workspace, task.venv_executables)
        return result

    def _stage_test(self, task: Task, workspace: Workspace) -> ValidationResult:
        """
        Stage: VALIDATING
        Run tests and return a ValidationResult (Stage 1 + Stage 2).
        """
        test_result = self._run_tests(task.plan, workspace, task)
        vr = validate_result(
            result=test_result,
            command_type="test",
            task_description=task.raw_input,
            generated_code=json.dumps(task.generated_files, indent=2),
            ai=self.ai,
        )
        return vr

    def _stage_complete(
        self, task: Task, workspace: Workspace, iterations: int
    ) -> None:
        """
        Stage: DONE
        Archive workspace and set success result on task.
        """
        zip_path = workspace.archive()
        task.result = TaskResult(
            success=True,
            output_path=zip_path,
            summary=(
                "Completed successfully"
                if iterations == 0
                else f"Fixed after {iterations} iteration(s)"
            ),
            iterations_used=iterations,
        )
        task.transition(TaskStatus.DONE)
        logger.info("✅ DONE [%s] — %s", task.id, task.result.summary)
        if self.context:
            self.context.add_message("assistant", task.result.summary)

    # ══════════════════════════════════════════════════════════════════════════
    # Fix loop
    # ══════════════════════════════════════════════════════════════════════════

    def _fix_loop(
        self,
        task: Task,
        workspace: Workspace,
        error_ctx: str,
        last_vr: Any = None,
    ) -> None:
        # Read once at loop entry — prevents mid-loop config changes from
        # affecting iteration count, and ensures monkeypatching in tests works.
        max_iters = int(config.max_fix_iterations)
        current_error = error_ctx
        current_vr = last_vr
        attempt_history: List[str] = []

        task.transition(TaskStatus.FIXING)
        logger.info("Entering fix loop (max %d iterations)", max_iters)

        for i in range(1, max_iters + 1):
            task.increment_fix_iteration()
            logger.info("Fix iteration %d/%d", i, max_iters)

            _error_category = classify_error(
                stderr=task.last_stderr or "",
                stdout=task.last_stdout or "",
            )
            logger.info("Error classified as: %s", _error_category)

            fixed_files = self.ai.generate_fix(
                plan=task.plan,
                current_files=task.generated_files,
                stdout=task.last_stdout,
                stderr=task.last_stderr,
                error=current_error,
                iteration=i,
                attempt_history=attempt_history,
                context=self.context,
                semantic_reason=current_vr.semantic_reason if current_vr else None,
                semantic_issues=current_vr.semantic_issues if current_vr else None,
                error_category=_error_category,
            )

            if not fixed_files:
                logger.warning("Fix iteration %d returned no changes", i)
                attempt_history.append(f"Iteration {i}: AI returned no changes.")
                continue

            task.generated_files.update(fixed_files)
            workspace.update_files(fixed_files)
            self._inject_conftest_if_needed(workspace, task)
            self._normalize_test_command(task, workspace)

            if "requirements.txt" in fixed_files:
                logger.info("requirements.txt changed — re-running install")
                self._run_install(task.plan, workspace, task.venv_executables)

            task.transition(TaskStatus.VALIDATING)
            current_vr = self._stage_test(task, workspace)

            if current_vr.is_success:
                self._stage_complete(task, workspace, iterations=i)
                return

            if (
                getattr(current_vr.stage1_result, "timed_out", False)
                or current_vr.stage1_result.returncode == -1
            ):
                raise MaxRetriesExceeded(
                    f"Execution timed out during fix iteration {i} — aborting (non-fixable)"
                )
            if getattr(current_vr.stage1_result, "security_blocked", False):
                raise MaxRetriesExceeded(
                    f"Security violation during fix iteration {i} — aborting: "
                    f"{current_vr.stage1_result.stderr[:200]}"
                )

            current_error = build_error_context(current_vr, "test")
            from nexus.core.contracts import ExecutionOutput
            task.record_execution(ExecutionOutput(
                returncode=current_vr.stage1_result.returncode,
                stdout=current_vr.stage1_result.stdout,
                stderr=current_vr.stage1_result.stderr,
                timed_out=getattr(current_vr.stage1_result, "timed_out", False),
            ))
            attempt_history.append(
                f"Iteration {i}: changed {list(fixed_files.keys())} — "
                f"still failed: {current_vr.stage1_result.stderr[-400:]}"
            )

            if i < max_iters:
                task.transition(TaskStatus.FIXING)

        raise MaxRetriesExceeded(
            f"Fix loop exhausted after {max_iters} iterations. "
            f"Last error: {current_error[:200]}"
        )

    # ══════════════════════════════════════════════════════════════════════════
    # Helpers (unchanged from original)
    # ══════════════════════════════════════════════════════════════════════════

    def _normalize_test_command(self, task: Task, workspace: Workspace) -> None:
        wdir = workspace.get_path()
        planned_cmd = task.plan.get("test_command", "").strip()
        resolved_cmd = self._resolve_test_command(planned_cmd, wdir)
        if resolved_cmd != planned_cmd:
            logger.info(
                "Normalized test_command: '%s' → '%s'", planned_cmd, resolved_cmd
            )
            task.plan["test_command"] = resolved_cmd

    def _resolve_test_command(self, planned_cmd: str, wdir: str) -> str:
        if planned_cmd:
            args = shlex.split(planned_cmd)
            if self._is_valid_command(args, wdir) and self._command_target_exists(args, wdir):
                return planned_cmd

        test_files = self._find_test_files(wdir)
        if test_files:
            return "pytest -v --tb=short"

        for name in ["main.py", "app.py", "run.py"]:
            if os.path.exists(os.path.join(wdir, name)):
                return f"python3 {name}"

        return ""

    def _command_target_exists(self, args: list, wdir: str) -> bool:
        if not args:
            return False
        executable = os.path.basename(args[0]).lower()
        if executable == "pytest":
            for arg in args[1:]:
                if not arg.startswith("-"):
                    target = os.path.join(wdir, arg)
                    if not os.path.exists(target):
                        return False
            return True
        if executable in _BARE_INTERPRETERS and len(args) >= 2:
            script = args[1]
            if not script.startswith("-"):
                return os.path.exists(os.path.join(wdir, script))
        return True

    def _inject_conftest_if_needed(self, workspace: Workspace, task: Task) -> None:
        wdir = workspace.get_path()
        conftest_path = os.path.join(wdir, "conftest.py")
        if os.path.exists(conftest_path):
            return

        has_subdir_tests = any(
            fname.endswith(".py")
            and ("/" in fname or os.sep in fname)
            and os.path.basename(fname).startswith("test_")
            for fname in task.generated_files
        )
        if not has_subdir_tests:
            return

        try:
            with open(conftest_path, "w") as f:
                f.write(_CONFTEST_CONTENT)
            task.generated_files["conftest.py"] = _CONFTEST_CONTENT
            logger.info("Injected conftest.py")
        except OSError as e:
            logger.warning("Failed to inject conftest.py: %s", e)

    def _run_install(
        self,
        plan: dict,
        workspace: Workspace,
        venv_exec: dict = None,
    ) -> ExecResult:
        req_file = os.path.join(workspace.get_path(), "requirements.txt")
        if not os.path.exists(req_file):
            return ExecResult(0, "Skipped: no requirements.txt", "")
        try:
            content = open(req_file).read().strip()
        except OSError:
            content = ""
        if not content:
            return ExecResult(0, "Skipped: empty requirements.txt", "")

        cmd = plan.get("install_command") or "pip install -r requirements.txt"
        args = shlex.split(cmd)
        if venv_exec and args and args[0] in ("pip", "pip3"):
            args[0] = venv_exec.get(args[0], args[0])

        logger.info("Running install: %s", args)
        return run_command(args, cwd=workspace.get_path(), timeout=120)

    def _run_tests(self, plan: dict, workspace: Workspace, task: Task) -> Any:
        wdir = workspace.get_path()
        cmd = plan.get("test_command", "").strip()

        if not cmd:
            logger.warning("No test command — treating as passed")
            return run_command(["echo", "No executable target — skipped"], cwd=wdir)

        args = shlex.split(cmd)
        if not args:
            return run_command(["echo", "Empty command — skipped"], cwd=wdir)

        executable = os.path.basename(args[0]).lower()
        timeout = config.exec_timeout
        venv_path = os.path.join(wdir, ".venv")

        try:
            if executable == "pytest":
                test_dir = "."
                for arg in args[1:]:
                    if not arg.startswith("-"):
                        test_dir = arg
                        break
                code, out, err = self._executor.execute_tests(
                    wdir, venv_path, test_dir, timeout
                )
            elif executable in ("python", "python3") and len(args) >= 2:
                script = args[1]
                code, out, err = self._executor.execute_script(
                    wdir, venv_path, script, timeout
                )
            else:
                res = run_command(args, cwd=wdir, timeout=timeout)
                return res

            timed_out = code in (124, -1)
            return ExecResult(
                returncode=code, stdout=out, stderr=err, timed_out=timed_out
            )

        except Exception as e:
            logger.error("Executor failure: %s", e)
            err_msg = str(e)
            is_security = any(
                kw in err_msg
                for kw in ["Forbidden function call", "Forbidden import", "Illegal file access"]
            )
            return ExecResult(
                returncode=-2,
                stdout="",
                stderr=err_msg,
                timed_out=False,
                security_blocked=is_security,
            )

    def _find_test_files(self, wdir: str) -> List[str]:
        found = []
        try:
            for entry in os.scandir(wdir):
                if (
                    entry.is_file()
                    and entry.name.startswith("test_")
                    and entry.name.endswith(".py")
                ):
                    found.append(entry.name)
                elif entry.is_dir() and not entry.name.startswith("."):
                    try:
                        for sub in os.scandir(entry.path):
                            if (
                                sub.is_file()
                                and sub.name.startswith("test_")
                                and sub.name.endswith(".py")
                            ):
                                found.append(os.path.join(entry.name, sub.name))
                    except OSError:
                        pass
        except OSError:
            pass
        return found

    def _is_valid_command(self, args: list, cwd: str) -> bool:
        if not args:
            return False
        executable = os.path.basename(args[0]).lower()
        if executable in _BARE_INTERPRETERS and len(args) == 1:
            return False
        return True

    def _handle_non_task(self, task: Task, intent_result: Any) -> Task:
        """Handle CHAT, CODE, or SYSTEM intents outside the full pipeline."""
        if intent_result.intent == IntentType.CHAT:
            task.result = TaskResult(
                success=True,
                summary=self.ai.generate_chat_response(task.raw_input, self.context),
            )
        elif intent_result.intent == IntentType.CODE:
            summary = "CODE: Analysis complete."
            has_inline_code = any(
                kw in task.raw_input
                for kw in ["def ", "class ", "import ", "```", "return "]
            )
            content = ""
            target_file = ""

            if has_inline_code:
                content = task.raw_input
                target_file = "INLINE"
            else:
                if self.context and self.context.project_snapshot:
                    for f in self.context.project_snapshot.structure:
                        if f in task.raw_input:
                            target_file = f
                            try:
                                from nexus.executor.workspace import ProjectScanner
                                scanner = ProjectScanner(
                                    self.context.project_snapshot.root
                                )
                                content = scanner.read_file(f)
                                break
                            except Exception:
                                continue

            if content:
                if "refactor" in task.raw_input.lower() and target_file != "INLINE":
                    res = self.code_intel.refactor(
                        content, task.raw_input, filename=target_file
                    )
                    summary = (
                        f"REFACTOR [{target_file}]: {res['reasoning']}\n\n"
                        f"```python\n{res['refactored_code']}\n```"
                    )
                elif (
                    "debug" in task.raw_input.lower() or "fix" in task.raw_input.lower()
                ) and target_file != "INLINE":
                    res = self.code_intel.debug(
                        content, "No error log provided.", filename=target_file
                    )
                    summary = (
                        f"DEBUG [{target_file}]: {res['diagnosis']}\n\nFIX: {res['fix']}"
                    )
                elif "review" in task.raw_input.lower() and target_file != "INLINE":
                    res = self.code_intel.review(content, filename=target_file)
                    summary = (
                        f"REVIEW [{target_file}]: Score {res['quality_score']}/10\n"
                        f"Issues: {', '.join(res['issues'])}"
                    )
                else:
                    summary = f"EXPLAIN [{target_file}]:\n" + self.code_intel.explain(
                        content, task.raw_input, filename=target_file
                    )
            else:
                summary = "No matching file found in project context to analyze."

            task.result = TaskResult(success=True, summary=summary)

        elif intent_result.intent == IntentType.SYSTEM:
            task.result = TaskResult(
                success=True,
                summary=(
                    f"SYSTEM: {intent_result.reasoning} "
                    "(Direct system commands blocked for safety)"
                ),
            )

        task.transition(TaskStatus.DONE)
        return task


    def _fail_task(self, task: "Task", reason: str) -> None:
        """Mark task FAILED with human-readable reason. Safe from any pipeline state."""
        try:
            task.transition(TaskStatus.FAILED)
        except Exception:
            task.status = TaskStatus.FAILED
        task.result = TaskResult(
            success=False,
            summary=reason,
            iterations_used=task.fix_iteration,
        )
        logger.error("Task [%s] FAILED: %s", task.id, reason)

    def _shutdown_cleanup(self) -> None:
        try:
            from nexus.executor.docker_exec import (
                cleanup_orphaned_containers,
                is_docker_available,
            )
            if is_docker_available():
                cleaned = cleanup_orphaned_containers()
                if cleaned > 0:
                    logger.info("Shutdown cleanup: removed %d containers", cleaned)
        except (ImportError, Exception):
            pass