"""
nexus/core/engine.py
"""
import os
import shlex
import json
from typing import List, Optional, Any

from nexus.ai.code_intel import CodeIntelligence
from nexus.ai.orchestrator import AIOrchestrator
from nexus.ai.router import IntentRouter, IntentType, IntentResult
from nexus.ai.prompts import classify_error
from nexus.core.exceptions import (
    MaxRetriesExceeded,
    NexusBaseException,
    OllamaConnectionError,
    SafetyViolation,
    TaskGenerationError,
    TaskPlanningError,
)
from nexus.core.task import Task, TaskResult, TaskStatus
from nexus.executor.safe_exec import ExecResult, create_task_venv, get_venv_executables, run_command
from nexus.executor.executor_factory import get_executor
from nexus.executor.validator import build_error_context, validate_result
from nexus.executor.workspace import Workspace
from nexus.utils.config import config
from nexus.utils.history import TaskHistory
from nexus.utils.logger import get_logger

logger = get_logger(__name__)

_BARE_INTERPRETERS = {
    "python3", "python", "python2",
    "node", "ruby", "perl", "bash", "sh",
}

_CONFTEST_CONTENT = (
    "# Auto-generated by NEXUS\n"
    "# Empty conftest.py — tells pytest to add project root to sys.path\n"
)


class TaskEngine:
    def __init__(self, context: Optional[Any] = None) -> None:
        import atexit
        
        self.ai = AIOrchestrator()
        self.context = context
        self.history = TaskHistory()
        self.code_intel = CodeIntelligence(self.ai)
        self._executor = get_executor()
        logger.info("TaskEngine initialized with %s", self._executor.__class__.__name__)

        # Startup cleanup: remove any containers left over from a previous crash
        try:
            from nexus.executor.docker_exec import cleanup_orphaned_containers, is_docker_available
            if is_docker_available():
                cleaned = cleanup_orphaned_containers()
                if cleaned > 0:
                    logger.warning("Cleaned up %d orphaned containers from previous session", cleaned)
            
            # Register shutdown handler for clean exit
            atexit.register(self._shutdown_cleanup)
        except ImportError:
            # Docker SDK not installed — skip container cleanup logic
            logger.debug("Docker SDK not found — skipping container cleanup")

    # ── Main entry point ──────────────────────────────────────────────────────

    def run(self, user_input: str, intent_result: Any = None) -> Any:
        from nexus.core.task import Task
        task = Task(raw_input=user_input)

        logger.info("=" * 60)
        logger.info("Starting task [%s]: %s", task.id, task.raw_input[:60])
        logger.info("=" * 60)

        try:
            # ── INTENT ROUTING ──────────────────────────────────────────────────
            if intent_result is None:
                from nexus.ai.router import IntentRouter
                router = IntentRouter(self.ai)
                intent_result = router.route(task.raw_input)
                
            # Safely normalise intent to string regardless of enum or raw string input
            _intent = intent_result.intent
            intent_val = _intent.value if isinstance(_intent, IntentType) else str(_intent).upper()
            task.intent = intent_result
    
            if self.context:
                self.context.add_message("user", task.raw_input)
    
            if intent_val != IntentType.TASK.value:
                logger.info("Non-task intent detected: %s", intent_val)
                res = self._handle_non_task(task, intent_result)
                if self.context:
                    self.context.add_message("assistant", res.result.summary)
                    self.context.add_task_result(
                        task.id, res.result.summary, intent_val, res.status.name
                    )
                return res
    
            workspace = Workspace(task.id)
            workspace.create()
            task.workspace_path = workspace.get_path()
    
            # Create isolated venv for this task — prevents dependency conflicts
            venv_path = create_task_venv(workspace.get_path())
            task.venv_executables = get_venv_executables(venv_path)
    
            # ── PLANNING ─────────────────────────────────────────────────────
            task.transition(TaskStatus.PLANNING)
            plan = self.ai.generate_plan(task.raw_input, context=self.context)
            task.plan = plan

            # ── GENERATION ───────────────────────────────────────────────────
            task.transition(TaskStatus.GENERATING)
            files = self.ai.generate_code(plan, context=self.context)
            task.generated_files = files
            workspace.write_files(files)
            self._inject_conftest_if_needed(workspace, task)

            self._normalize_test_command(task, workspace)

            # ── INSTALL ──────────────────────────────────────────────────────
            task.transition(TaskStatus.EXECUTING)
            install_result = self._run_install(plan, workspace, task.venv_executables)
            if not validate_result(install_result, "install"):
                error_ctx = build_error_context(install_result, "install")
                task.record_execution_output(
                    install_result.stdout, install_result.stderr, error_ctx
                )
                self._fix_loop(task, workspace, error_ctx)

            # ── VALIDATE ─────────────────────────────────────────────────────
            task.transition(TaskStatus.VALIDATING)
            test_result = self._run_tests(task.plan, workspace, task)

            vr = validate_result(
                result=test_result,
                command_type="test",
                task_description=task.raw_input,
                generated_code=json.dumps(task.generated_files, indent=2),
                ai=self.ai
            )

            if vr.is_success:
                self._complete_task(task, workspace, iterations=task.fix_iteration)
            else:
                error_ctx = build_error_context(vr, "test")
                task.record_execution_output(
                    test_result.stdout, test_result.stderr, error_ctx
                )
                # TERMINAL FAILURE GUARD: timeout is not fixable by AI
                if getattr(test_result, "timed_out", False) or test_result.returncode == -1:
                    self._fail_task(task, "Execution timed out — task killed (non-fixable)")
                    return task
                if getattr(test_result, "security_blocked", False):
                    self._fail_task(task, f"Security violation blocked execution (non-fixable): {test_result.stderr[:200]}")
                    return task
                self._fix_loop(task, workspace, error_ctx, vr)

        except OllamaConnectionError as e:
            self._fail_task(task, f"Ollama unreachable: {e}")
        except (TaskPlanningError, TaskGenerationError) as e:
            self._fail_task(task, f"AI error: {e}")
        except SafetyViolation as e:
            self._fail_task(task, f"Security blocked: {e}")
        except MaxRetriesExceeded as e:
            self._fail_task(task, str(e))
        except NexusBaseException as e:
            self._fail_task(task, f"NEXUS error: {e}")
        except Exception as e:
            logger.exception("Unexpected error in engine")
            self._fail_task(task, f"Unexpected: {e}")

        finally:
            if self.context and task.result:
                # Safely get intent value for history
                intent_obj = getattr(task, "intent", None)
                intent_type = getattr(intent_obj, "intent", "UNKNOWN")
                intent_str = intent_type.value if hasattr(intent_type, "value") else str(intent_type)
                
                self.context.add_task_result(
                    task.id,
                    task.result.summary,
                    intent_str,
                    task.status.name
                )
            
            # Record persistent history (survives session ends)
            self.history.record(
                task, 
                self.context.session_id if self.context else "NO_SESSION"
            )
            # Only cleanup on failure — DONE tasks keep workspace until
            # user retrieves the zip output
            if task.status == TaskStatus.FAILED:
                try:
                    workspace.cleanup()
                except Exception:
                    logger.warning("Workspace cleanup failed for task %s", task.id)

        return task

    # ── Test command normalization ─────────────────────────────────────────────

    def _normalize_test_command(self, task: Task, workspace: Workspace) -> None:
        wdir = workspace.get_path()
        planned_cmd = task.plan.get("test_command", "").strip()
        resolved_cmd = self._resolve_test_command(planned_cmd, wdir)

        if resolved_cmd != planned_cmd:
            logger.info(
                "Normalized test_command: '%s' → '%s'",
                planned_cmd,
                resolved_cmd,
            )
            task.plan["test_command"] = resolved_cmd

    def _resolve_test_command(self, planned_cmd: str, wdir: str) -> str:
        if planned_cmd:
            args = shlex.split(planned_cmd)
            if self._is_valid_command(args, wdir) and self._command_target_exists(args, wdir):
                return planned_cmd

        test_files = self._find_test_files(wdir)
        if test_files:
            logger.debug("Test files found at: %s — using 'pytest -v --tb=short'", test_files)
            return "pytest -v --tb=short"

        for name in ["main.py", "app.py", "run.py"]:
            if os.path.exists(os.path.join(wdir, name)):
                return f"python3 {name}"

        return ""

    def _command_target_exists(self, args: list, wdir: str) -> bool:
        if not args:
            return False

        executable = os.path.basename(args[0]).lower()

        if executable == "pytest":
            for arg in args[1:]:
                if not arg.startswith("-"):
                    target = os.path.join(wdir, arg)
                    if not os.path.exists(target):
                        logger.debug(
                            "pytest target '%s' does not exist in workspace", arg
                        )
                        return False
            return True

        if executable in _BARE_INTERPRETERS and len(args) >= 2:
            script = args[1]
            if not script.startswith("-"):
                return os.path.exists(os.path.join(wdir, script))

        return True

    # ── Workspace helpers ─────────────────────────────────────────────────────

    def _inject_conftest_if_needed(self, workspace: Workspace, task: Task) -> None:
        wdir = workspace.get_path()
        conftest_path = os.path.join(wdir, "conftest.py")

        if os.path.exists(conftest_path):
            logger.debug("conftest.py already present — skipping injection")
            return

        has_subdir_tests = any(
            fname.endswith(".py")
            and ("/" in fname or os.sep in fname)
            and os.path.basename(fname).startswith("test_")
            for fname in task.generated_files
        )

        if not has_subdir_tests:
            return

        try:
            with open(conftest_path, "w") as f:
                f.write(_CONFTEST_CONTENT)
            task.generated_files["conftest.py"] = _CONFTEST_CONTENT
            logger.info("Injected conftest.py — test files in subdirectory detected")
        except OSError as e:
            logger.warning("Failed to inject conftest.py: %s", e)

    # ── Command runners ───────────────────────────────────────────────────────

    def _run_install(
        self,
        plan: dict,
        workspace: Workspace,
        venv_exec: dict = None,
    ) -> ExecResult:
        req_file = os.path.join(workspace.get_path(), "requirements.txt")
        if not os.path.exists(req_file):
            logger.debug("No requirements.txt — skipping install")
            return ExecResult(0, "Skipped: no requirements.txt", "")
        try:
            content = open(req_file).read().strip()
        except OSError:
            content = ""
        if not content:
            logger.debug("requirements.txt is empty — skipping install")
            return ExecResult(0, "Skipped: empty requirements.txt", "")

        cmd = plan.get("install_command") or "pip install -r requirements.txt"
        args = shlex.split(cmd)

        # Redirect pip into the task-isolated venv
        if venv_exec and args and args[0] in ("pip", "pip3"):
            args[0] = venv_exec.get(args[0], args[0])

        logger.info("Running install: %s", args)
        return run_command(args, cwd=workspace.get_path(), timeout=120)

    def _run_tests(
        self,
        plan: dict,
        workspace: Workspace,
        task: Task,
    ) -> Any: # Returns ExecResult-like object
        wdir = workspace.get_path()
        cmd = plan.get("test_command", "").strip()

        if not cmd:
            logger.warning("No test command available — treating as passed")
            return run_command(["echo", "No executable target — skipped"], cwd=wdir)

        args = shlex.split(cmd)
        if not args:
            return run_command(["echo", "Empty command — skipped"], cwd=wdir)

        # Map to Executor methods
        executable = os.path.basename(args[0]).lower()
        timeout = config.exec_timeout
        venv_path = os.path.join(wdir, ".venv")

        try:
            if executable == "pytest":
                # Extract test dir if present
                test_dir = "."
                for arg in args[1:]:
                    if not arg.startswith("-"):
                        test_dir = arg
                        break
                code, out, err = self._executor.execute_tests(wdir, venv_path, test_dir, timeout)
            elif executable in ("python", "python3") and len(args) >= 2:
                script = args[1]
                code, out, err = self._executor.execute_script(wdir, venv_path, script, timeout)
            else:
                # Fallback for raw commands (Local only for now via direct run_command)
                logger.debug("Command '%s' not recognized by executor interface, using fallback runner", args[0])
                res = run_command(args, cwd=wdir, timeout=timeout)
                return res

            # Convert back to ExecResult for compatibility with validator
            # returncode -1 = killed by NEXUS timeout (local executor)
            # returncode 124 = killed by GNU timeout wrapper
            timed_out = (code == 124) or (code == -1)
            return ExecResult(returncode=code, stdout=out, stderr=err, timed_out=timed_out)

        except Exception as e:
            logger.error("Executor failure: %s", e)
            err_msg = str(e)
            # SecurityViolation from AST gate — mark as security_blocked
            # so the engine can treat it as terminal (unfixable by AI)
            is_security = any(kw in err_msg for kw in [
                "Forbidden function call",
                "Forbidden import",
                "Illegal file access",
            ])
            return ExecResult(
                returncode=-2,
                stdout="",
                stderr=err_msg,
                timed_out=False,
                security_blocked=is_security,
            )

    def _find_test_files(self, wdir: str) -> List[str]:
        found = []
        try:
            for entry in os.scandir(wdir):
                if entry.is_file() and entry.name.startswith("test_") and entry.name.endswith(".py"):
                    found.append(entry.name)
                elif entry.is_dir() and not entry.name.startswith("."):
                    try:
                        for sub in os.scandir(entry.path):
                            if sub.is_file() and sub.name.startswith("test_") and sub.name.endswith(".py"):
                                found.append(os.path.join(entry.name, sub.name))
                    except OSError:
                        pass
        except OSError:
            pass
        return found

    def _is_valid_command(self, args: list, cwd: str) -> bool:
        if not args:
            return False
        executable = os.path.basename(args[0]).lower()
        if executable in _BARE_INTERPRETERS and len(args) == 1:
            return False
        return True

    # ── Fix loop ──────────────────────────────────────────────────────────────

    def _fix_loop(self, task: Task, workspace: Workspace, error_ctx: str, last_vr: Any = None) -> None:
        max_iters = config.max_fix_iterations
        current_error = error_ctx
        current_vr = last_vr
        attempt_history: List[str] = []

        task.transition(TaskStatus.FIXING)
        logger.info("Entering fix loop (max %d iterations)", max_iters)

        for i in range(1, max_iters + 1):
            task.increment_fix_iteration()
            logger.info("Fix iteration %d/%d", i, max_iters)

            # Classify the error to give the AI a targeted fix strategy
            _error_category = classify_error(
                stderr=task.last_stderr or "",
                stdout=task.last_stdout or "",
            )
            logger.info("Error classified as: %s", _error_category)

            fixed_files = self.ai.generate_fix(
                plan=task.plan,
                current_files=task.generated_files,
                stdout=task.last_stdout,
                stderr=task.last_stderr,
                error=current_error,
                iteration=i,
                attempt_history=attempt_history,
                context=self.context,
                semantic_reason=current_vr.semantic_reason if current_vr else None,
                semantic_issues=current_vr.semantic_issues if current_vr else None,
                error_category=_error_category,
            )

            if not fixed_files:
                logger.warning("Fix iteration %d returned no changes", i)
                attempt_history.append(f"Iteration {i}: AI returned no changes.")
                continue

            task.generated_files.update(fixed_files)
            workspace.update_files(fixed_files)
            self._inject_conftest_if_needed(workspace, task)
            self._normalize_test_command(task, workspace)

            if "requirements.txt" in fixed_files:
                logger.info("requirements.txt changed — re-running install")
                install_result = self._run_install(
                    task.plan, workspace, task.venv_executables
                )
                if not validate_result(install_result, "install"):
                    logger.warning(
                        "Re-install after fix failed: %s",
                        install_result.stderr[:300],
                    )

            task.transition(TaskStatus.VALIDATING)
            test_result = self._run_tests(
                task.plan, workspace, task
            )

            current_vr = validate_result(
                result=test_result,
                command_type="test",
                task_description=task.raw_input,
                generated_code=json.dumps(task.generated_files, indent=2),
                ai=self.ai
            )

            if current_vr.is_success:
                self._complete_task(task, workspace, iterations=i)
                return

            # TERMINAL FAILURE GUARD: timeout inside fix loop — abort immediately
            if getattr(test_result, "timed_out", False) or test_result.returncode == -1:
                raise MaxRetriesExceeded(
                    f"Execution timed out during fix iteration {i} — aborting fix loop (non-fixable)"
                )
            if getattr(test_result, "security_blocked", False):
                raise MaxRetriesExceeded(
                    f"Security violation during fix iteration {i} — aborting fix loop (non-fixable): "
                    f"{test_result.stderr[:200]}"
                )

            current_error = build_error_context(current_vr, "test")
            task.record_execution_output(
                test_result.stdout, test_result.stderr, current_error
            )
            attempt_history.append(
                f"Iteration {i}: changed {list(fixed_files.keys())} — "
                f"still failed: {test_result.stderr[-400:]}"
            )

            if i < max_iters:
                task.transition(TaskStatus.FIXING)

        raise MaxRetriesExceeded(
            f"Fix loop exhausted after {max_iters} iterations. "
            f"Last error: {current_error[:200]}"
        )

    # ── Outcome helpers ───────────────────────────────────────────────────────

    def _complete_task(self, task: Task, workspace: Workspace, iterations: int) -> None:
        zip_path = workspace.archive()
        task.result = TaskResult(
            success=True,
            output_path=zip_path,
            summary=(
                "Completed successfully"
                if iterations == 0
                else f"Fixed after {iterations} iteration(s)"
            ),
            iterations_used=iterations,
        )
        task.transition(TaskStatus.DONE)
        logger.info("✅ DONE [%s] — %s", task.id, task.result.summary)
        if self.context:
            self.context.add_message("assistant", task.result.summary)

    def _fail_task(self, task: Task, reason: str) -> None:
        logger.error("❌ FAILED [%s]: %s", task.id, reason)
        task.result = TaskResult(
            success=False,
            summary=f"FAILED: {reason}",
            iterations_used=getattr(task, "fix_iteration", 0),
        )
        task.transition(TaskStatus.FAILED)
        if self.context:
            self.context.add_message("assistant", task.result.summary)


    def _handle_non_task(self, task: Task, intent_result: Any) -> Task:
        """Handle CHAT, CODE, or SYSTEM intents outside the full pipeline."""
        from nexus.ai.router import IntentType

        if intent_result.intent == IntentType.CHAT:
            task.result = TaskResult(
                success=True,
                summary=self.ai.generate_chat_response(task.raw_input, self.context)
            )
        elif intent_result.intent == IntentType.CODE:
            # ── CODE INTELLIGENCE ─────────────────────────────────────────────
            summary = "CODE: Analysis complete."
            
            # 1. Check for inline code snippet
            has_inline_code = any(kw in task.raw_input for kw in ['def ', 'class ', 'import ', '```', 'return '])
            
            content = ""
            target_file = ""
            
            if has_inline_code:
                content = task.raw_input
                target_file = "INLINE"
            else:
                # 2. Try to find a file to analyze from project context
                if self.context and self.context.project_snapshot:
                    # Scan structure for any filename mentioned in the input
                    for f in self.context.project_snapshot.structure:
                        if f in task.raw_input:
                            target_file = f
                            try:
                                from nexus.executor.workspace import ProjectScanner
                                scanner = ProjectScanner(self.context.project_snapshot.root)
                                content = scanner.read_file(f)
                                break
                            except Exception:
                                continue

            if content:
                # Dispatch based on keywords or default to explain
                if "refactor" in task.raw_input.lower() and target_file != "INLINE":
                    res = self.code_intel.refactor(content, task.raw_input, filename=target_file)
                    summary = f"REFACTOR [{target_file}]: {res['reasoning']}\n\n```python\n{res['refactored_code']}\n```"
                elif ("debug" in task.raw_input.lower() or "fix" in task.raw_input.lower()) and target_file != "INLINE":
                    res = self.code_intel.debug(content, "No error log provided.", filename=target_file)
                    summary = f"DEBUG [{target_file}]: {res['diagnosis']}\n\nFIX: {res['fix']}"
                elif "review" in task.raw_input.lower() and target_file != "INLINE":
                    res = self.code_intel.review(content, filename=target_file)
                    summary = f"REVIEW [{target_file}]: Score {res['quality_score']}/10\nIssues: {', '.join(res['issues'])}"
                else:
                    # Default / Inline path
                    summary = f"EXPLAIN [{target_file}]:\n" + self.code_intel.explain(content, task.raw_input, filename=target_file)
            else:
                summary = "No matching file found in project context to analyze."

            task.result = TaskResult(success=True, summary=summary)
        elif intent_result.intent == IntentType.SYSTEM:
            task.result = TaskResult(
                success=True,
                summary=f"SYSTEM: {intent_result.reasoning} (Direct system commands blocked for safety)"
            )

        task.transition(TaskStatus.DONE)
        return task

    def _shutdown_cleanup(self) -> None:
        """Internal cleanup handler registered with atexit to prune containers on exit."""
        try:
            from nexus.executor.docker_exec import cleanup_orphaned_containers, is_docker_available
            if is_docker_available():
                cleaned = cleanup_orphaned_containers()
                if cleaned > 0:
                    logger.info("Shutdown cleanup: removed %d containers", cleaned)
        except (ImportError, Exception):
            pass  # Never raise during interpreter shutdown
